### ISSUE TITLE
[#18] IOS & Android TCP Socket Communication

### ISSUE THREAD

**Issue by ChangYeop-Yang** [ChangYeop-Yang/CPL-20181-Team2#18]
- 주제
TCP 소켓 통신을 통한 소켓 서버와의 통신 기능 구현 (Local Push 기능 구현 목적) 

- 참가자
@ChangYeop-Yang
@Coldy24 
@jesboom 

1. [Real-Time Communication with IOS](https://www.raywenderlich.com/157128/real-time-communication-streams-tutorial-ios)

2. [Local Notification with IOS](http://avilos.codes/mobile/ios-swift/ios-swift-%EB%A1%9C%EC%BB%AC%EC%95%8C%EB%A6%BClocal-notification/)

**Comment by Coldy24** [comment]
웹서버에서 아두이노 포트를 8080으로 인식
