### ISSUE TITLE
[#2] Android UI/UX Design

### ISSUE THREAD

**Issue by ChangYeop-Yang** [ChangYeop-Yang/CPL-20181-Team2#2]
-프로젝트 명:
Android UI/UX Design

- 참여자:
@jesboom

**Comment by jesboom** [comment]
Objective

1. Create Android application using Android studio
2. Design using MVC model
3. Using chart, Realm DATABASE library
4. User UI / UX development
5. Home environment control and situation recognition function

Progress: Create home screen UI, add graph library

**Comment by jesboom** [comment]
![screenshot_1522739333](https://user-images.githubusercontent.com/23624908/38234749-bdcf390a-3759-11e8-98ae-27ceab7207e9.png)
REMOTE화면 V.1.0

**Comment by jesboom** [comment]
![screenshot_1522739356](https://user-images.githubusercontent.com/23624908/38234781-db502d2c-3759-11e8-9265-ae4c35deaac7.png)
SETTING화면 V.1.0
