### ISSUE TITLE
[#3] Build WEB Server (Python, JavaScript)

### ISSUE THREAD

**Issue by ChangYeop-Yang** [ChangYeop-Yang/CPL-20181-Team2#3]
- 프로젝트 명:
Build WEB Server (Python, JavaScript)

- 참여자:
@ChangYeop-Yang
@heosooho
@Coldy24

**Comment by heosooho** [comment]
웹서버를 Node.js로 구현
웹서버와   Realm DB 연동 구현
최종 아두이노 와 app간의 통신을 위한 웹서버 완성
진행상황:에코서버 구현 &  Realm 설치

**Comment by Coldy24** [comment]
Objective
1. Build Web server at Raspberry-Pi with Node.js
2. Getting sensor data as Bluetooth with Python
3. Send appropriate Information(Data, Alarm)
4. Get any control information(ex. Philips Hue control...)

Progress : Build Eco Server & Realm Database Install

**Comment by heosooho** [comment]
진행상황: 측정 데이터 Json &Realm구조 정의 ,서버 구현

**Comment by Coldy24** [comment]
Realm DB 폐기, SQLite DB 사용

**Comment by Coldy24** [comment]
-웹서버에서 /get~~을 통해 JSON으로 최근 30개 데이터 전송
-아두이노에서 TCP 연결을 통해 웹서버로 데이터 전송
-아두이노 이벤트 발생시, TCP연결 포트번호 8080을 통해 웹서버로 전송, 웹서버는 이벤트 발생 인지시 포트번호 8090에 연결되어있는 모바일 클라이언트들에게 값 전송
-모바일 이벤트 발생시, TCP연결 포트번호 8090을 통해 웹서버로 전송, 웹서버는 이벤트 발생 인지시 포트번호 8080에 연결되어있는 아두이노 클라이언트들에게 값 전송
