### ISSUE TITLE
[#5] Assemble Arduino Part

### ISSUE THREAD

**Issue by ChangYeop-Yang** [ChangYeop-Yang/CPL-20181-Team2#5]
- 프로젝트 명:
Assemble Arduino Part

- 참여자:
@ChangYeop-Yang
@Coldy24 
@jesboom 
@heosooho

**Comment by ChangYeop-Yang** [comment]
![kakaotalk_photo_2018-04-10-23-18-11_81](https://user-images.githubusercontent.com/20036523/38562411-763d5df8-3d15-11e8-87b5-6ab378e04fa3.jpeg)

![analoginputsensor](https://user-images.githubusercontent.com/20036523/38562413-79edf4a8-3d15-11e8-9cfd-11073cae0200.jpg)

![500px-connect_dfr0049](https://user-images.githubusercontent.com/20036523/38562414-7a24eaee-3d15-11e8-9389-dd8964ec99ca.png)

[URL](https://www.dfrobot.com/wiki/index.php/Analog_Gas_Sensor(MQ5)_(SKU:SEN0130))

**Comment by ChangYeop-Yang** [comment]
[Arduino Sound Sensor](https://circuitdigest.com/microcontroller-projects/arduino-sound-level-measurement)

**Comment by heosooho** [comment]
![unadjustednonraw_thumb_4b0](https://user-images.githubusercontent.com/31512726/38987766-e4657e4e-440b-11e8-831d-d03c61fe09bf.jpg)
![unadjustednonraw_thumb_4b1](https://user-images.githubusercontent.com/31512726/38987776-eb7afe7a-440b-11e8-84ec-d81edb88269c.jpg)

아두이노 키트를 이용해 온,습도 , 공기질 ,db 값 측정

**Comment by jesboom** [comment]
![arduino](https://user-images.githubusercontent.com/23624908/39009136-c4872c14-4445-11e8-94b7-db1cc2decd1b.jpg)
아두이노 IR수신센서를 통한 데이터 추출

**Comment by heosooho** [comment]
거실 센서 구현
![img_0694](https://user-images.githubusercontent.com/31512726/39628891-6efa51a8-4fe5-11e8-944b-bf044145b9a8.JPG)

**Comment by ChangYeop-Yang** [comment]
![dsc_6168](https://user-images.githubusercontent.com/20036523/39664730-b103bab6-50c2-11e8-8ab6-d0f6e4fc4898.jpg)

![dsc_6169](https://user-images.githubusercontent.com/20036523/39664731-b12ba012-50c2-11e8-8de5-71f79329dabf.jpg)

**Comment by heosooho** [comment]
거실 센서 추가(IR,진동,조도)
진동이 감지될 경우 부저 울림/ IR센서로 삼성티비 제어(볼륨,채널,전원)/조도센서로 밝기측정 
![unadjustednonraw_thumb_4d4](https://user-images.githubusercontent.com/31512726/39922089-67c58f56-5558-11e8-87ce-f693a91a5b5c.jpg)

**Comment by heosooho** [comment]
[Arduino-IR-remote-master.zip](https://github.com/ChangYeop-Yang/CPL-20181-Team2/files/1995158/Arduino-IR-remote-master.zip)
IR 라이브러리
