### ISSUE TITLE
[#6] Build Arduino

### ISSUE THREAD

**Issue by ChangYeop-Yang** [ChangYeop-Yang/CPL-20181-Team2#6]
- 프로젝트 명: Build Arduino

- 사용 할 언어: C++

- 참여자:
@ChangYeop-Yang
@Coldy24 
@jesboom 
@heosooho

**Comment by Coldy24** [comment]
### 아두이노 esp8266 설치

- 링크주소 ::https://github.com/esp8266/Arduino

- 파일 -> 환경설정탭의 추가적인 보드매니저URL에 다음 주소 추가 ::http://arduino.esp8266.com/stable/package_esp8266com_index.json

- 툴 -> 보드탭의 보드매니저 선택해서 ESP8266 설치

**Comment by Coldy24** [comment]
esp8266 폐기, serial통신으로만 웹서버 전송으로 변경.
아두이노to 웹서버용 포트 : 8080
