### ISSUE TITLE
[#7] Write Meeting Document and Picture

### ISSUE THREAD

**Issue by ChangYeop-Yang** [ChangYeop-Yang/CPL-20181-Team2#7]
[#7] Write Meeting Document and Picture

- 책임자
@Coldy24 
@ChangYeop-Yang

- 내용

![kakaotalk_photo_2018-03-29-14-52-20_23](https://user-images.githubusercontent.com/20036523/38072456-4e325236-3361-11e8-9980-1e2ecfbca2d9.jpeg)

![kakaotalk_photo_2018-03-29-14-52-21_83](https://user-images.githubusercontent.com/20036523/38072458-4e61a91e-3361-11e8-8f6a-77ace300e654.jpeg)

![kakaotalk_photo_2018-03-29-14-52-23_10](https://user-images.githubusercontent.com/20036523/38072459-4e90091c-3361-11e8-9cb0-5300c5effaad.jpeg)

![kakaotalk_photo_2018-03-29-14-52-24_12](https://user-images.githubusercontent.com/20036523/38072460-4ebd76e0-3361-11e8-82a8-f683a09bbec5.jpeg)

![kakaotalk_photo_2018-03-29-14-52-26_77](https://user-images.githubusercontent.com/20036523/38072461-4efdb32c-3361-11e8-9527-a18b9ea9bfc2.jpeg)

![kakaotalk_photo_2018-03-29-14-52-28_61](https://user-images.githubusercontent.com/20036523/38072462-4f29da92-3361-11e8-8053-f7cb5d1c1e9e.jpeg)

**Comment by Coldy24** [comment]
Planing to group meeting with Keimyung University student team members at 2018.04.04

**Comment by Coldy24** [comment]
![image](https://user-images.githubusercontent.com/26784883/38122488-4ac210dc-3410-11e8-983b-84ec8705b08e.png)
2018.03.29 Meeting

**Comment by heosooho** [comment]
![img_3427](https://user-images.githubusercontent.com/31512726/38549744-bd48b84e-3cef-11e8-8393-bbaf3a86fc59.JPG)
![img_8212](https://user-images.githubusercontent.com/31512726/38549745-bd803af8-3cef-11e8-80f2-a7f3da8c05b1.JPG)
![img_8568](https://user-images.githubusercontent.com/31512726/38549748-bdaf1314-3cef-11e8-971c-163cd7e138b7.JPG)

**Comment by heosooho** [comment]
2018.04.24 meeting
![unadjustednonraw_thumb_4b4](https://user-images.githubusercontent.com/31512726/39182319-7b5293e8-47f7-11e8-8e26-332f8e9ca846.jpg)

**Comment by heosooho** [comment]
2018.05.01 Meeting
![unadjustednonraw_thumb_4b7](https://user-images.githubusercontent.com/31512726/39626266-2e582250-4fdc-11e8-8e09-98d87821cb5e.jpg)

**Comment by heosooho** [comment]
2018.05.02 Meeting
![unadjustednonraw_thumb_4b8](https://user-images.githubusercontent.com/31512726/39626305-4d67260a-4fdc-11e8-9eea-db1adbe66c56.jpg)

**Comment by heosooho** [comment]
2018.5.08 Meeting
![unadjustednonraw_thumb_4be](https://user-images.githubusercontent.com/31512726/39761933-526f13f2-5314-11e8-9991-698c44b58589.jpg)

**Comment by heosooho** [comment]
2018.5.23 Meeting
![img_0306](https://user-images.githubusercontent.com/31512726/40404736-558d6b16-5e94-11e8-8186-57f09bd212bd.PNG)
